participant Alice as Alice
participant Alice's Browser as A
participant Alice's App as App
participant Alice's Firewall as FW
participant Alice's Turn as Turn
participant Web Server Browse as Web
participant Media Switch as MCU
A <-> Web: Load Page 
App <-> Web: Authenticate
Web <-> MCU: stuff
Web -> App: Offer 
App -> Alice: Check Hair
Alice -> App: Hair if fluffy 

App -> A: create PeerConnection()
A -> Turn: Alloc
App -> A: SetRemote( Offer ) 
App -> A: addStream audio/video
App -> A: createAnswer(  noIceDelay )
A -> App: answer 
ans:App -> A: setLocal
App -> A: onRemoteStream main
App -> A: onRemoteStream thumbnail one
App -> A: onRemoteStream thumbnail two
f1:A -> FW: ICE
FW@f1 -> MCU: ICE
MCU -> FW: ICE

stuff: Web -> MCU: stuff
App@ans -> Web@stuff: answer 

Turn -> A: IPs and Ports
sendUp:A -> App: new ice candiate 
A -> Turn: Perm

recvUp:Web -> MCU: Stuff
App@sendUp -> Web@recvUp: update

f2: A <-> Turn : ICE
Turn@f2 <-> MCU : ICE 


f3: A <-> Turn : DTLS
Turn@f3 <-> MCU : DTLS 

f4: A <-> Turn : SRTP
Turn@f4 <-> MCU : SRTP 





